### ISSUE TITLE
View file

### ISSUE THREAD

**Issue by ByteMark84** [dp-0/user-activity#1]
I have a route set up in web.php but it just shows a blank page. Do I need to copy over the view file from vendor/dp-0/user-activity/views/user-activity.blade.php?

This is in web.php
`Route::get('activity-logs', UserActivity::class)->name('user.activity_logs');`

**Comment by dp-0** [comment]
@ByteMark84 

Your route setup is good, and it should work as expected. There's no need to copy the view file manually from vendor/dp-0/user-activity/views/user-activity.blade.php.

For detailed instructions on configuring and using the user activity package, please follow the guide provided here: [Enhance User Tracking in Laravel with the User Activity Package](https://medium.com/@phuyeldinesh/enhance-user-tracking-in-laravel-with-the-user-activity-package-a-comprehensive-guide-683050f88a98). This guide will help ensure that everything is set up properly.
